spring:
  application:
    name: dealer-inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/dealer_inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.mohamedsaad.inventory: DEBUG